#!/usr/bin/with-contenv bash

RTORRENT_USER=${RTORRENT_USER:-rtorrent}

if [ -n "$RTORRENT_UID" ]; then
    OPTS="-u $RTORRENT_UID"
fi

if [ -n "$RTORRENT_GID" ]; then
    OPTS="$OPTS -G $RTORRENT_USER"
    addgroup -g $RTORRENT_GID $RTORRENT_USER
fi

adduser -H -h /nonexistent -D -s /sbin/nologin $OPTS $RTORRENT_USER
#adduser -D -s /sbin/nologin $OPTS $RTORRENT_USER
